### PR TITLE
TYPO3 v11 compatibility 

### PR DESCRIPTION
**Pull request by svenpet90**
The Extension is already working fine with TYPO3 v11. 

I just updated the TYPO3 version requirements in the composer.json to make it requirable and "beautified" the code using the tool "Easy Coding Standard"

### CODE REVIEW

**Comment by joey-bolts** [comment]
@svenpet90 Thanks for testing, when we will find the time we will walk through it once more and then release it for v11

**Comment by derseeli** [comment]
I tried the fork, looks good to me.
Would need the update for a new project and would not like to run it on the fork.

I would be very grateful if you can find time for it at short notice

**Comment by joey-bolts** [comment]
@svenpet90  @derseeli  Will try to release it this week.

**Comment by joey-bolts** [comment]
@svenpet90 @derseeli Release has been made, thanks for contributing and testing.

**Comment by svenpet90** [comment]
You're very welcome! Thanks so much for releasing :-)

**Pull request merged**
